/*          Copyright Ubiquiti Networks Inc. 2014
**          All Rights Reserved.
*/

#include <common.h>
#include <command.h>
#include <malloc.h>
#include <asm/string.h>
#include <ubnt_api_calls.h>
#include <version_autogenerated.h>
#include <net.h>

#include "ubnt_api_calls.h"

#define UNUSED(x) ((void)(x))
#define UBNT_CMD_MAX_ARG 7
#define UBNT_CMD_MAX_LEN 24
#define UBNT_CMD_STR_MAX 48

#define UBNT_APP_MAGIC 0x87564523

extern unsigned long uboot_end_data;
extern unsigned long _start;

    /* Loads the application into memory */

int ubnt_app_load()
{
    char addr[10];

    ulong ubntapp_flash_addr = CFG_FLASH_BASE +
                               ((ulong)&uboot_end_data - (ulong)&_start);

    /* If the ubnt application is not loaded yet, load it now */
    memmove((void *) UBNT_APP_MAGIC_OFFSET, (void *)ubntapp_flash_addr,
            UBNT_APP_SIZE);

    if (UBNT_APP_MAGIC != *((uint32_t *)UBNT_APP_MAGIC_OFFSET)) {
        printf(" *WARNING*: UBNT APP Magic mismatch, addr=%x, magic=%x \n",
               ((uint32_t *)UBNT_APP_MAGIC_OFFSET),
               *((uint32_t *)UBNT_APP_MAGIC_OFFSET));
        return -1;
    }

    sprintf(addr, "%x", UBNT_APP_START_OFFSET);
    setenv("ubntaddr", addr);

    return 0;
}
