#!/bin/sh
# Print additional version information for non-release trees.

usage() {
	echo "Usage: $0 [srctree]" >&2
	exit 1
}

cd "${1:-.}" || usage

# Check for git and a git repo.
if head=`git rev-parse --verify HEAD 2>/dev/null`; then
	# Do we have an untagged version?
	if  [ "`git name-rev --tags HEAD`" = "HEAD undefined" ]; then
		printf '%s%s' -g `echo "$head" | cut -c1-8`
	fi

	# Are there uncommitted changes?
	if git diff-files | read dummy; then
		printf '%s' -dirty
	fi
else
	svn_ver=`svnversion -n`
	if [ "${svn_ver}" != "exported" ]; then
		case ${svn_ver} in
		*[:MPS]*)
			printf '%s%s' -s ${svn_ver}
			;;
		*)
			printf '%s%s' -s `svn info | awk -F': ' '/Last Changed Rev:/{print $2}'`
			;;
		esac
	fi
fi
